version: '3.8'

services:
  api:
    build: ./api
    container_name: wine_api
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/models
    environment:
      - PYTHONUNBUFFERED=1

  app:
    build: ./app
    container_name: wine_app
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - PYTHONUNBUFFERED=1